[package]
name = "static-site-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
fs_extra = "1.3.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tinytemplate = "1.2.1"
